# 기본 틀만 적어놓음
# 실제 구동시에는 datasource의 password를 제대로 기입할 것.
# 또한 ec2 업로드시 보안을 위해 jwt.secret 또한 변경할 것.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web-order-db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: #비밀번호는 실제 실행시에만 작성할 것.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  web:
    resources:
      static-locations: file:media/,classpath:/static
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt:
  secret: xIjvWyzFNiIL16uC7Z4vtoY6nkCKk+wjN/ruzg8lkX6t09fC+qHWMRG+4RtoYakCOQWq1bmyYH34oab36pf8Tw==